language: ruby
sudo: false
cache: bundler

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby-head
  - ruby-head

# https://github.com/travis-ci/travis-ci/issues/5861
before_install:
  - gem install bundler
  - gem update bundler

notifications:
  email: false
