language: ruby
sudo: false
cache: bundler

rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-head
  - ruby-head

# https://github.com/travis-ci/travis-ci/issues/5861
before_install:
  - gem install bundler
  - gem update bundler

notifications:
  email: false
